version: '3'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/app/bin/migrate up && /app/bin/api"]

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passw0rd  
      - POSTGRES_DB=books
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U user -d books" ]
        interval: 3s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"
    restart: always