version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db 

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passw0rd  
      - POSTGRES_DB=books
    ports:
      - "5432:5432"
    restart: always